/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed-variant": "#0b513d",
        "surface-tint": "#2b6954",
        "inverse-primary": "#95d3ba",
        "surface-variant": "#e1e3e2",
        "primary": "#003527",
        "outline": "#707974",
        "on-primary": "#ffffff",
        "surface": "#f8faf9",
        "on-surface": "#191c1c",
        "on-error": "#ffffff",
        "secondary-container": "#a6f2d1",
        "on-tertiary-container": "#9ab9a6",
        "on-background": "#191c1c",
        "secondary-fixed": "#a6f2d1",
        "surface-container-low": "#f2f4f3",
        "inverse-on-surface": "#eff1f0",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#8bd6b6",
        "secondary": "#1b6b51",
        "on-tertiary-fixed-variant": "#314d3e",
        "surface-dim": "#d8dada",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#002117",
        "surface-container": "#eceeed",
        "surface-container-high": "#e6e9e8",
        "on-secondary-fixed-variant": "#00513b",
        "primary-container": "#064e3b",
        "on-secondary-container": "#237157",
        "surface-container-highest": "#e1e3e2",
        "on-error-container": "#93000a",
        "on-primary-container": "#80bea6",
        "background": "#f8faf9",
        "tertiary": "#183326",
        "surface-bright": "#f8faf9",
        "primary-fixed-dim": "#95d3ba",
        "on-tertiary-fixed": "#042014",
        "outline-variant": "#bfc9c3",
        "on-surface-variant": "#404944",
        "inverse-surface": "#2e3131",
        "primary-fixed": "#b0f0d6",
        "tertiary-fixed": "#caead6",
        "tertiary-fixed-dim": "#afceba",
        "on-secondary": "#ffffff",
        "tertiary-container": "#2f4a3b",
        "on-secondary-fixed": "#002116",
        "error-container": "#ffdad6",
        "error": "#ba1a1a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sm": "12px",
        "container-max": "1280px",
        "xs": "4px",
        "base": "8px",
        "lg": "48px",
        "gutter": "32px",
        "md": "24px",
        "xl": "80px"
      },
      "fontFamily": {
        "body-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "h1": ["Plus Jakarta Sans"],
        "display": ["Plus Jakarta Sans"],
        "h3": ["Plus Jakarta Sans"],
        "h2": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"]
      },
      "fontSize": {
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "h1": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "display": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "h3": ["24px", { "lineHeight": "1.4", "letterSpacing": "0em", "fontWeight": "500" }],
        "h2": ["32px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
